els-ASAP auto commit file/tag libseccomp-2.3.1-3.el7.src.rpm

diff --git a/src/src/arch-syscall-validate b/src/src/arch-syscall-validate
--- a/src/src/arch-syscall-validate
+++ b/src/src/arch-syscall-validate
@@ -4,7 +4,7 @@
 # libseccomp syscall validation script
 #
 # Copyright (c) 2014 Red Hat <pmoore@redhat.com>
-# Author: Paul Moore <pmoore@redhat.com>
+# Author: Paul Moore <paul@paul-moore.com>
 #
 
 #
@@ -63,7 +63,28 @@ libseccomp syscall validation script
 optional arguments:
   -h             show this help message and exit
   -a             architecture
+  -l             output the library's syscall definitions
+  -s             output the system's syscall definitions
 EOF
+}
+
+#
+# Dump the library syscall table for a given architecture
+#
+# Arguments:
+#     1    architecture
+#     2    offset (optional)
+#
+#
+#  Dump the library's syscall table to stdout.
+#
+function dump_lib_arch() {
+	local offset_str=""
+
+	[[ -z $1 ]] && return
+
+	[[ -n $2 ]] && offset_str="-o $2"
+	$LIB_SYS_DUMP -a $1 $offset_str | sed -e '/[^\t]\+\t-[0-9]\+/d'
 }
 
 #
@@ -75,7 +96,7 @@ EOF
 #  Dump the architecture's syscall table to stdout.
 #
 function dump_sys_x86() {
-	cat $1/arch/x86/syscalls/syscall_32.tbl | \
+	cat $1/arch/x86/entry/syscalls/syscall_32.tbl | \
 		grep -v "^#" | awk '{ print $3"\t"$1 }' | sed '/^[ \t]*$/d' | \
 		sort
 }
@@ -86,7 +107,7 @@ function dump_sys_x86() {
 #  Dump the library's syscall table to stdout.
 #
 function dump_lib_x86() {
-	$LIB_SYS_DUMP -a x86 | sed -e '/[^\t]\+\t-[0-9]\+/d'
+	dump_lib_arch x86
 }
 
 #
@@ -98,7 +119,7 @@ function dump_lib_x86() {
 #  Dump the architecture's syscall table to stdout.
 #
 function dump_sys_x86_64() {
-	cat $1/arch/x86/syscalls/syscall_64.tbl | \
+	cat $1/arch/x86/entry/syscalls/syscall_64.tbl | \
 		grep -v "^#" | awk '{ print $2,$3,$1 }' | sed -e '/^x32/d' | \
 		awk '{ print $2"\t"$3 }' | sed '/^[ \t]*$/d' | sort
 }
@@ -109,7 +130,7 @@ function dump_sys_x86_64() {
 #  Dump the library's syscall table to stdout.
 #
 function dump_lib_x86_64() {
-	$LIB_SYS_DUMP -a x86_64 | sed -e '/[^\t]\+\t-[0-9]\+/d'
+	dump_lib_arch x86_64
 }
 
 #
@@ -121,7 +142,7 @@ function dump_lib_x86_64() {
 #  Dump the architecture's syscall table to stdout.
 #
 function dump_sys_x32() {
-	cat $1/arch/x86/syscalls/syscall_64.tbl | \
+	cat $1/arch/x86/entry/syscalls/syscall_64.tbl | \
 		grep -v "^#" | awk '{ print $2,$3,$1 }' | sed -e '/^64/d' | \
 		awk '{ print $2"\t"$3 }' | sed '/^[ \t]*$/d' | sort
 }
@@ -133,7 +154,7 @@ function dump_sys_x32() {
 #
 function dump_lib_x32() {
 	# 1073741824 == 0x40000000
-	$LIB_SYS_DUMP -a x32 -o 1073741824 | sed -e '/[^\t]\+\t-[0-9]\+/d'
+	dump_lib_arch x32 1073741824
 }
 
 #
@@ -159,7 +180,6 @@ function dump_sys_arm() {
 				echo "$line"; \
 			fi; \
 		done | \
-		cat - | \
 		sed -e '/#define __NR_sync_file_range2[ \t]\+__NR_arm_sync_file_range/d' | \
 		sort
 }
@@ -171,8 +191,7 @@ function dump_sys_arm() {
 #
 function dump_lib_arm() {
 	# NOTE: arm_sync_file_range() and sync_file_range2() share values
-	$LIB_SYS_DUMP -a arm | sed -e '/[^\t]\+\t-[0-9]\+/d' | \
-		sed -e '/sync_file_range2[ \t]\+341/d'
+	dump_lib_arch arm | sed -e '/sync_file_range2[ \t]\+341/d'
 }
 
 #
@@ -211,7 +230,7 @@ function dump_sys_aarch64() {
 #  Dump the library's syscall table to stdout.
 #
 function dump_lib_aarch64() {
-	$LIB_SYS_DUMP -a aarch64 | sed -e '/[^\t]\+\t-[0-9]\+/d'
+	dump_lib_arch aarch64
 }
 
 #
@@ -245,7 +264,7 @@ function dump_sys_mips() {
 #  Dump the library's syscall table to stdout.
 #
 function dump_lib_mips() {
-	$LIB_SYS_DUMP -a mips -o 4000 | sed -e '/[^\t]\+\t-[0-9]\+/d'
+	dump_lib_arch mips 4000
 }
 
 #
@@ -279,7 +298,7 @@ function dump_sys_mips64() {
 #  Dump the library's syscall table to stdout.
 #
 function dump_lib_mips64() {
-	$LIB_SYS_DUMP -a mips64 -o 5000 | sed -e '/[^\t]\+\t-[0-9]\+/d'
+	dump_lib_arch mips64 5000
 }
 
 #
@@ -313,7 +332,115 @@ function dump_sys_mips64n32() {
 #  Dump the library's syscall table to stdout.
 #
 function dump_lib_mips64n32() {
-	$LIB_SYS_DUMP -a mips64n32 -o 6000 | sed -e '/[^\t]\+\t-[0-9]\+/d'
+	dump_lib_arch mips64n32 6000
+}
+
+#
+# Dump the ppc system syscall table
+#
+# Arguments:
+#     1    path to the kernel source
+#
+#  Dump the architecture's syscall table to stdout.
+#
+function dump_sys_ppc() {
+	gcc -E -dM $1/arch/powerpc/include/uapi/asm/unistd.h | \
+		grep "^#define __NR_" | \
+		sed -e 's/#define[ \t]\+__NR_\([a-z0-9_]\+\)[ \t]\+\([0-9]\+\)/\1\t\2/' | \
+		sort
+}
+
+#
+# Dump the ppc library syscall table
+#
+#  Dump the library's syscall table to stdout.
+#
+function dump_lib_ppc() {
+	dump_lib_arch ppc
+}
+
+#
+# Dump the ppc64 system syscall table
+#
+# Arguments:
+#     1    path to the kernel source
+#
+#  Dump the architecture's syscall table to stdout.
+#
+function dump_sys_ppc64() {
+	gcc -E -dM -D__powerpc64__ $1/arch/powerpc/include/uapi/asm/unistd.h | \
+		grep "^#define __NR_" | \
+		sed -e 's/#define[ \t]\+__NR_\([a-z0-9_]\+\)[ \t]\+\([0-9]\+\)/\1\t\2/' | \
+		sort
+}
+
+#
+# Dump the ppc64 library syscall table
+#
+#  Dump the library's syscall table to stdout.
+#
+function dump_lib_ppc64() {
+	dump_lib_arch ppc64
+}
+
+#
+# Dump the s390 system syscall table
+#
+# Arguments:
+#     1    path to the kernel source
+#
+#  Dump the architecture's syscall table to stdout.
+#
+function dump_sys_s390() {
+	gcc -E -dM $1/arch/s390/include/uapi/asm/unistd.h | grep __NR | \
+		sed -e 's/#define[ \t]\+__NR_\([^ \t]\+\)[ \t]\+(__NR_timer_create[ \t]*+[ \t]*\([0-9]\+\)).*/\1\t254 + \2/' | \
+		while read line; do \
+			if echo "$line" | grep -q "+"; then \
+				echo "$line" | awk '{ print $1"\t"$2+$4 }'; \
+			else \
+				echo "$line"; \
+			fi; \
+		done | \
+		sed 's/#define __NR_//g' | sed 's/ /\t/g' | sort
+}
+
+#
+# Dump the s390 library syscall table
+#
+#  Dump the library's syscall table to stdout.
+#
+function dump_lib_s390() {
+	dump_lib_arch s390
+}
+
+#
+# Dump the s390x system syscall table
+#
+# Arguments:
+#     1    path to the kernel source
+#
+#  Dump the architecture's syscall table to stdout.
+#
+function dump_sys_s390x() {
+	gcc -E -dM -D __s390x__ $1/arch/s390/include/uapi/asm/unistd.h | grep __NR | \
+		sed -e 's/#define[ \t]\+__NR_\([^ \t]\+\)[ \t]\+(__NR_timer_create[ \t]*+[ \t]*\([0-9]\+\)).*/\1\t254 + \2/' | \
+		while read line; do \
+			if echo "$line" | grep -q "+"; then \
+				echo "$line" | awk '{ print $1"\t"$2+$4 }'; \
+			else \
+				echo "$line"; \
+			fi; \
+		done | \
+		sed 's/#define __NR_//g' | sed 's/ /\t/g' | sort
+}
+
+#
+# Dump the s390x library syscall table
+#
+#  Dump the library's syscall table to stdout.
+#
+function dump_lib_s390x() {
+	dump_lib_arch s390x
 }
 
 #
@@ -351,10 +478,25 @@ function dump_sys() {
 	mips64n32)
 		dump_sys_mips64n32 "$2"
 		;;
+	ppc)
+		dump_sys_ppc "$2"
+		;;
+	ppc64)
+		dump_sys_ppc64 "$2"
+		;;
+	s390)
+		dump_sys_s390 "$2"
+		;;
+	s390x)
+		dump_sys_s390x "$2"
+		;;
 	*)
 		echo ""
+		return 1
 		;;
 	esac
+
+	return 0
 }
 
 #
@@ -368,33 +510,48 @@ function dump_sys() {
 function dump_lib() {
 	case $1 in
 	x86)
-		dump_lib_x86 "$2"
+		dump_lib_x86
 		;;
 	x86_64)
-		dump_lib_x86_64 "$2"
+		dump_lib_x86_64
 		;;
 	x32)
-		dump_lib_x32 "$2"
+		dump_lib_x32
 		;;
 	arm)
-		dump_lib_arm "$2"
+		dump_lib_arm
 		;;
 	aarch64)
-		dump_lib_aarch64 "$2"
+		dump_lib_aarch64
 		;;
 	mips)
-		dump_lib_mips "$2"
+		dump_lib_mips
 		;;
 	mips64)
-		dump_lib_mips64 "$2"
+		dump_lib_mips64
 		;;
 	mips64n32)
-		dump_lib_mips64n32 "$2"
+		dump_lib_mips64n32
+		;;
+	ppc)
+		dump_lib_ppc "$2"
+		;;
+	ppc64)
+		dump_lib_ppc64 "$2"
+		;;
+	s390)
+		dump_lib_s390 "$2"
+		;;
+	s390x)
+		dump_lib_s390x "$2"
 		;;
 	*)
 		echo ""
+		return 1
 		;;
 	esac
+
+	return 0
 }
 
 ####
@@ -410,12 +567,22 @@ if [[ ! -x $LIB_SYS_DUMP ]]; then
 	exit 1
 fi
 
-arches=""
+opt_arches=""
+opt_sys=""
+opt_lib=""
 
-while getopts "a:h" opt; do
+while getopts "a:slh" opt; do
 	case $opt in
 	a)
-		arches+="$OPTARG "
+		opt_arches+="$OPTARG "
+		;;
+	s)
+		opt_sys=1
+		opt_lib=0
+		;;
+	l)
+		opt_sys=0
+		opt_lib=1
 		;;
 	h|*)
 		usage
@@ -426,8 +593,13 @@ done
 shift $(($OPTIND - 1))
 
 # defaults
-if [[ $arches == "" ]]; then
-	arches="x86 x86_64 x32 arm aarch64 mips mips64 mips64n32"
+if [[ $opt_arches == "" ]]; then
+	opt_arches=" \
+		x86 x86_64 x32 \
+		arm aarch64 \
+		mips mips64 mips64n32 \
+		ppc ppc64 \
+		s390 s390x"
 fi
 
 # sanity checks
@@ -442,20 +614,35 @@ if [[ ! -d $kernel_dir ]]; then
 fi
 
 # generate some temp files
-tmp_orig=$(mktemp -t syscall_validate_XXXXXX)
-tmp_new=$(mktemp -t syscall_validate_XXXXXX)
+tmp_lib=$(mktemp -t syscall_validate_XXXXXX)
+tmp_sys=$(mktemp -t syscall_validate_XXXXXX)
 
-# loop through the architectures
-for i in $arches; do
+# loop through the architectures and compare
+for i in $opt_arches; do
 	# dump the syscall tables
-	dump_lib $i > $tmp_orig
-	dump_sys $i "$kernel_dir" > $tmp_new
+	dump_lib $i > $tmp_lib
+	if [[ $? -ne 0 ]]; then
+		echo "error: unknown arch $i"
+		exit 1
+	fi
+	dump_sys $i "$kernel_dir" > $tmp_sys
+	if [[ $? -ne 0 ]]; then
+		echo "error: unknown arch $i"
+		exit 1
+	fi
 
-	# do the comparison
-	diff -u --label="$i [library]" $tmp_orig --label "$i [system]" $tmp_new
+	if [[ $opt_lib -eq 1 ]]; then
+		cat $tmp_lib
+	elif [[ $opt_sys -eq 1 ]]; then
+		cat $tmp_sys
+	else
+		#  compare the lib and sys output
+		diff -u --label="$i [library]" $tmp_lib \
+			--label "$i [system]" $tmp_sys
+	fi
 done
 
 # cleanup and exit
-rm -f $tmp_orig $tmp_new
+rm -f $tmp_lib $tmp_sys
 
 exit 0
diff --git a/src/tests/regression b/src/tests/regression
--- a/src/tests/regression
+++ b/src/tests/regression
@@ -21,8 +21,15 @@
 # along with this library; if not, see <http://www.gnu.org/licenses>.
 #
 
-GLBL_ARCH_LE_SUPPORT="x86 x86_64 x32 arm aarch64 mipsel mipsel64 mipsel64n32"
-GLBL_ARCH_BE_SUPPORT="mips mips64 mips64n32"
+GLBL_ARCH_LE_SUPPORT=" \
+	x86 x86_64 x32 \
+	arm aarch64 \
+	mipsel mipsel64 mipsel64n32 \
+	ppc64le"
+GLBL_ARCH_BE_SUPPORT=" \
+	mips mips64 mips64n32 \
+	ppc ppc64 \
+	s390 s390x"
 
 GLBL_SYS_ARCH="../tools/scmp_arch_detect"
 GLBL_SYS_RESOLVER="../tools/scmp_sys_resolver"
@@ -164,6 +171,33 @@ function get_range() {
 }
 
 #
+# Get the number sequence for a given range with increments of 1, i.e.
+# implement a specialized seq(1).
+#
+# We use our own implementation based on miniseq in favour to the standard seq
+# tool as, at least, seq of coreutils v8.23 and v8.24 has problems on 32 bit
+# ARM for large numbers (see the mailing thread at
+# https://groups.google.com/forum/#!topic/libseccomp/VtrClkXxLGA).
+#
+# Arguments:
+#     1    starting value
+#     2    last value
+#
+function get_seq() {
+	# NOTE: this whole thing is a bit hacky, but we need to search around
+	#       for miniseq to fix 'make distcheck', someday we should fix this
+	if [[ -x ./miniseq ]]; then
+		./miniseq "$1" "$2"
+	elif [[ -x $basedir/miniseq ]]; then
+		$basedir/miniseq "$1" "$2"
+	else
+		# we're often run from a subshell, so we can't simply exit
+		echo "error: unable to find miniseq" >&2
+		kill $pid
+	fi
+}
+
+#
 # Run the specified test command (with valgrind if requested)
 #
 # Arguments:
@@ -245,7 +279,7 @@ function run_test_bpf_sim_fuzz() {
 	local testname=${line[0]}
 	local stress_count=${line[1]}
 
-	for i in $(seq 1 $stress_count); do
+	for i in $(get_seq 1 $stress_count); do
 		local sys=$(generate_random_data)
 		local -a arg=($(generate_random_data) $(generate_random_data) \
 			      $(generate_random_data) $(generate_random_data) \
@@ -462,13 +496,13 @@ function run_test_bpf_sim() {
 		# and arg ranges and generate/run every combination of requested
 		# tests; if no ranges were specifed, then the single test is
 		# run
-		for sys in $(seq -f "%1.0f" $low_syscall $high_syscall); do
-		for arg0 in $(seq -f "%1.0f" ${low_arg[0]} ${high_arg[0]}); do
-		for arg1 in $(seq -f "%1.0f" ${low_arg[1]} ${high_arg[1]}); do
-		for arg2 in $(seq -f "%1.0f" ${low_arg[2]} ${high_arg[2]}); do
-		for arg3 in $(seq -f "%1.0f" ${low_arg[3]} ${high_arg[3]}); do
-		for arg4 in $(seq -f "%1.0f" ${low_arg[4]} ${high_arg[4]}); do
-		for arg5 in $(seq -f "%1.0f" ${low_arg[5]} ${high_arg[5]}); do
+		for sys in $(get_seq $low_syscall $high_syscall); do
+		for arg0 in $(get_seq ${low_arg[0]} ${high_arg[0]}); do
+		for arg1 in $(get_seq ${low_arg[1]} ${high_arg[1]}); do
+		for arg2 in $(get_seq ${low_arg[2]} ${high_arg[2]}); do
+		for arg3 in $(get_seq ${low_arg[3]} ${high_arg[3]}); do
+		for arg4 in $(get_seq ${low_arg[4]} ${high_arg[4]}); do
+		for arg5 in $(get_seq ${low_arg[5]} ${high_arg[5]}); do
 			local -a arg=($arg0 $arg1 $arg2 $arg3 $arg4 $arg5)
 
 			# Get the generated sub-test num string
@@ -667,7 +701,7 @@ function run_test_live() {
 
 	# setup the arch specific return values
 	case "$arch" in
-	x86|x86_64|x32|arm|aarch64)
+	x86|x86_64|x32|arm|aarch64|ppc|ppc64|ppc64le|ppc|s390|s390x)
 		rc_kill=159
 		rc_allow=160
 		rc_trap=161
@@ -827,7 +861,6 @@ function run_tests() {
 verify_deps head
 verify_deps sed
 verify_deps awk
-verify_deps seq
 verify_deps tr
 
 # global variables
@@ -852,6 +885,9 @@ stats_error=0
 
 # set the test root directory
 basedir=$(dirname $0)
+
+# set the test harness pid
+pid=$$
 
 # parse the command line
 while getopts "ab:gl:m:s:t:T:vh" opt; do
